[package]
name = "hopi"
version = "0.1.0"
edition = "2024"
description = "Open Roblox Studio places from the command line"
license = "MIT"
repository = "https://github.com/UrbanIndigo/hopi"
homepage = "https://github.com/UrbanIndigo/hopi"
readme = "README.md"
keywords = ["roblox", "studio", "cli"]
categories = ["command-line-utilities"]

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
dirs = "5"
rbx_cookie = { version = "0.1", default-features = false }
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls", "gzip"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
skim = "0.10"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }

[profile.release]
lto = "thin"
strip = true

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
